HAI
I HAS A COUNTER ITZ 0
IM IN YR LOOP UPPIN YR COUNTER TIL BOTH SAEM COUNTER AN 100
    BOTH SAEM MOD OF COUNTER AN 3 AN 0
    O RLY?
        YA RLY
            BOTH SAEM MOD OF COUNTER AN 5 AN 0
            O RLY?
                YA RLY
                    VISIBLE "FIZZBUZZ"
                NO WAI
                    VISIBLE "FIZZ"
            OIC
        MEBBE BOTH SAEM MOD OF COUNTER AN 5 AN 0
            VISIBLE "BUZZ"
        NO WAI
            VISIBLE COUNTER
    OIC
IM OUTTA YR LOOP
KTHXBYE